# -*- coding: utf-8 -*-
"""image_gen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dm_petoADmR18PrpLU8Ywr3_sqTH-JZ9

#Image Generator from Pre-Trained Model
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/BAN 676 - Deep Learning/Group Project (not shared)')
print(os.getcwd())

# Imports
from keras.layers import Activation,Dense,Conv2D,UpSampling2D,LeakyReLU, Reshape, Flatten, Input, BatchNormalization,Dropout
from keras.models import Sequential, Model
#from keras.optimizers import Adam
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import pickle
import numpy as np

"""##Load Generator

https://www.tensorflow.org/guide/keras/save_and_serialize
"""

from tensorflow import keras
generator = keras.models.load_model('/content/drive/MyDrive/BAN 676 - Deep Learning/Group Project (not shared)/generator_64_64_z64_final_epoch.h5')

"""##Generate Image """

# Create a random noise and generate a sample
batch_size = 64
z_dimension = 64
noise = np.random.normal(0, 1, (batch_size, z_dimension))
gen_imgs = generator.predict(noise)
# Visualize the generated sample
plt.imshow(gen_imgs[0, :, :, 0], cmap='gray')